import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class AnaForm extends javax.swing.JFrame {

    
    
    DefaultTableModel model;
    
    
    public AnaForm() {
        
        initComponents();
        populateTable();
        
        
    }
    //tabloyu güncelle
    public void populateTable(){
   
    model = (DefaultTableModel)tblUrunler.getModel();
    model.setRowCount(0);
    
        try {
            ArrayList<Urunler> urunler = getUrunler();
           
            for (Urunler urunler1 : urunler) {
                Object[] row = {urunler1.getStokNo(),
                    urunler1.getÜrünAdi(),
                    urunler1.getBeden(),
                    urunler1.getRenk(),
                    urunler1.getCinsiyet(),
                    urunler1.getStokAdedi()};
                model.addRow(row);
            }
            
        } catch (SQLException ex) {
          
        }
    
    
    
    }
    
    
    
    
    
    public ArrayList<Urunler> getUrunler() throws SQLException{
    
        Connection connection = null;
        Dbhelper dbhelper = new Dbhelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Urunler> urunler = null;
        
        try {
            connection = dbhelper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select StokNo,ÜrünAdi,Beden,Renk,Cinsiyet,StokAdedi from Ürünler");
            urunler = new ArrayList<Urunler>();
            while (resultSet.next()) {                
                urunler.add(new Urunler(resultSet.getInt("StokNo"),
                        resultSet.getString("ÜrünAdi"),
                        resultSet.getString("Beden"),
                        resultSet.getString("Renk"),
                        resultSet.getString("Cinsiyet"),
                        resultSet.getInt("StokAdedi")));
            }
            
        } catch (SQLException exception) {
            
            dbhelper.showErrorMessage(exception);
        }finally{
        
        statement.close();
        connection.close();
        
        }
        return urunler;
        
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUrunler = new javax.swing.JTable();
        btnSiparisVer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        cmbName = new javax.swing.JComboBox<>();
        lblSize = new javax.swing.JLabel();
        cmbSize = new javax.swing.JComboBox<>();
        lblStokCount = new javax.swing.JLabel();
        txtStokCount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblAdd = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbCinsiyet = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblUpdate = new javax.swing.JLabel();
        lblUpdateStokNo = new javax.swing.JLabel();
        txtUpdateStokNo = new javax.swing.JTextField();
        lblUpdateName = new javax.swing.JLabel();
        cmbUpdateName = new javax.swing.JComboBox<>();
        lblUpdateSize = new javax.swing.JLabel();
        cmbUpdateSize = new javax.swing.JComboBox<>();
        lblUpdateColor = new javax.swing.JLabel();
        cmbUpdateColor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbUpdateCinsiyet = new javax.swing.JComboBox<>();
        lblUpdateStokCount = new javax.swing.JLabel();
        txtUpdateStokCount = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnRemoveLine = new javax.swing.JButton();
        lblRemove = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        lblSearch.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setText("ARA :");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        tblUrunler.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblUrunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StokNo", "ÜrünAdi", "Beden", "Renk", "Cinsiyet", "StokAdedi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUrunler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUrunlerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUrunler);

        btnSiparisVer.setBackground(new java.awt.Color(102, 102, 102));
        btnSiparisVer.setForeground(new java.awt.Color(255, 255, 255));
        btnSiparisVer.setText("SİPARİŞ VER");
        btnSiparisVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiparisVerActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GİRİŞ MENÜSÜ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("ÜrünAdi :");

        cmbName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KAZAK", "GÖMLEK", "KABAN", "MONT", "YELEK", "CEKET", "HIRKA", "PANTOLON", "SWEATSHIRT", "T-SHIRT", "EŞOFMAN", "TAYT", "CROP", " " }));

        lblSize.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSize.setForeground(new java.awt.Color(255, 255, 255));
        lblSize.setText("Beden :");

        cmbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "XXL", "XXXL", " " }));

        lblStokCount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblStokCount.setForeground(new java.awt.Color(255, 255, 255));
        lblStokCount.setText("StokAdedi :");

        txtStokCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokCountActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Ekle");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblAdd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("ÜRÜN EKLE");

        lblColor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Renk :");

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KIRMIZI", "MAVİ", "YEŞİL", "SARI", "TURUNCU", "MOR", "PEMBE", "KAHVERENGİ", "GRİ", "SİYAH", "BEYAZ", "TURKUAZ", "ALTIN", "GÜMÜŞ", "KOBALT MAVİSİ", " " }));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cinsiyet :");

        cmbCinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERKEK", "KADIN", "UNİSEX" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblStokCount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStokCount, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(cmbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSize)
                    .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStokCount)
                    .addComponent(txtStokCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUpdate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setText("GÜNCELLE");

        lblUpdateStokNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUpdateStokNo.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateStokNo.setText("StokNo :");

        txtUpdateStokNo.setEditable(false);

        lblUpdateName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUpdateName.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateName.setText("ÜrünAdi :");

        cmbUpdateName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KAZAK", "GÖMLEK", "KABAN", "MONT", "YELEK", "CEKET", "HIRKA", "PANTOLON", "SWEATSHIRT", "T-SHIRT", "EŞOFMAN", "TAYT", "CROP", " " }));

        lblUpdateSize.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUpdateSize.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateSize.setText("Beden :");

        cmbUpdateSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "XXL", "XXXL", " " }));

        lblUpdateColor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUpdateColor.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateColor.setText("Renk :");

        cmbUpdateColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KIRMIZI", "MAVİ", "YEŞİL", "SARI", "TURUNCU", "MOR", "PEMBE", "KAHVERENGİ", "GRİ", "SİYAH", "BEYAZ", "TURKUAZ", "ALTIN", "GÜMÜŞ", "KOBALT MAVİSİ", " " }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cinsiyet :");

        cmbUpdateCinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERKEK", "KADIN", "UNİSEX" }));

        lblUpdateStokCount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUpdateStokCount.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateStokCount.setText("StokAdedi :");

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("GÜNCELLE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUpdateColor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateStokNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUpdateName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUpdateSize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblUpdateStokCount))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateStokNo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateStokCount, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUpdateSize, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUpdateColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUpdateCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(219, 219, 219))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateStokNo)
                    .addComponent(txtUpdateStokNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblUpdateName))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cmbUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateSize)
                    .addComponent(cmbUpdateSize, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateColor)
                    .addComponent(cmbUpdateColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbUpdateCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateStokCount)
                    .addComponent(txtUpdateStokCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRemoveLine.setBackground(new java.awt.Color(102, 102, 102));
        btnRemoveLine.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveLine.setText("SATIRI SİL");
        btnRemoveLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLineActionPerformed(evt);
            }
        });

        lblRemove.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblRemove.setText("SİL");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnRemoveLine)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnRemoveLine)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1525, 1525, 1525)
                .addComponent(btnSiparisVer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnSiparisVer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        
       String searchKey = txtSearch.getText();
    TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<DefaultTableModel>(model);
    
    tblUrunler.setRowSorter(tableRowSorter);

    
    tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchKey));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      
        Connection connection = null;
        Dbhelper dbhelper = new Dbhelper();
        PreparedStatement statement = null;
        try {
            connection = dbhelper.getConnection();
            
            int stokCount = Integer.parseInt(txtStokCount.getText());
        if (stokCount < 0) {
            
            JOptionPane.showMessageDialog(this, "Stok Sayısı negatif olamaz.", "Giriş Hatası", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            String sql = "insert into ürünler (ÜrünAdi,Beden,Renk,Cinsiyet,StokAdedi) values (?,?,?,?,?)";
            statement = connection.prepareStatement(sql);
            
            statement.setString(1,(String) cmbName.getSelectedItem());
            statement.setString(2, (String) cmbSize.getSelectedItem());
            statement.setString(3, (String) cmbColor.getSelectedItem());
            statement.setString(4, (String) cmbCinsiyet.getSelectedItem());
            statement.setInt(5,Integer.parseInt(txtStokCount.getText()));
            
            int result = statement.executeUpdate();
            
            populateTable();
            
        } catch (SQLException exception) {
            
            dbhelper.showErrorMessage(exception);
            
            
        }finally{
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
                
            }
        
        
        
        
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      
    Connection connection = null;
    Dbhelper dbhelper = new Dbhelper();
    PreparedStatement statement = null;
    
    try {
        connection = dbhelper.getConnection();
        String sql = "UPDATE ürünler SET ÜrünAdi=?, Beden=?, Renk=?,Cinsiyet=? ,StokAdedi=? WHERE StokNo=?";
        statement = connection.prepareStatement(sql);
        statement.setString(1, (String)cmbUpdateName.getSelectedItem());
        statement.setString(2, (String)cmbUpdateSize.getSelectedItem());
        statement.setString(3, (String)cmbUpdateColor.getSelectedItem());
        statement.setString(4, (String) cmbCinsiyet.getSelectedItem());
         int stokAdedi = Integer.parseInt(txtUpdateStokCount.getText());
    
        if (stokAdedi < 0) {
            JOptionPane.showMessageDialog(null, "Stok Adedi negatif olamaz.", "Hata", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        statement.setInt(5, Integer.parseInt(txtUpdateStokCount.getText()));
        statement.setInt(6, Integer.parseInt(txtUpdateStokNo.getText()));
    
        int result = statement.executeUpdate();
        
        if (result > 0) {
          
            populateTable();
        }
        
    } catch (SQLException exception) {
        dbhelper.showErrorMessage(exception);
    } finally {
        try {
            statement.close();
            connection.close();
        } catch (SQLException ex) {
           
        }
    }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    
    private void tblUrunlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUrunlerMouseClicked
    
        int selectedRow = tblUrunler.getSelectedRow();

       
        int stokNo = (int) model.getValueAt(selectedRow, 0);
        String urunAdi = (String) model.getValueAt(selectedRow, 1);
        String beden = (String) model.getValueAt(selectedRow, 2);
        String renk = (String) model.getValueAt(selectedRow, 3);
        String cinsiyet = (String) model.getValueAt(selectedRow, 4);
        int stokAdedi = (int) model.getValueAt(selectedRow, 5);

    
        cmbUpdateName.setSelectedItem(urunAdi);
        cmbUpdateSize.setSelectedItem(beden);
        cmbUpdateColor.setSelectedItem(renk);
        cmbUpdateCinsiyet.setSelectedItem(cinsiyet);
        txtUpdateStokCount.setText(String.valueOf(stokAdedi));
        txtUpdateStokNo.setText(String.valueOf(stokNo));
        
    
        
        
    }//GEN-LAST:event_tblUrunlerMouseClicked

    

    
    
    
    
    
    
    
    
    
    
    private void veritabanindanKaydiKaldır(int silinecekStokNo) {
    Connection baglanti = null;
    Dbhelper dbhelper = new Dbhelper();
    PreparedStatement statement = null;

    try {
        baglanti = dbhelper.getConnection();
        String sql = "DELETE FROM ürünler WHERE StokNo=?";
        statement = baglanti.prepareStatement(sql);
        statement.setInt(1, silinecekStokNo);

        int sonuc = statement.executeUpdate();

        if (sonuc > 0) {
          
        } else {
           
        }
    } catch (SQLException exception) {
        dbhelper.showErrorMessage(exception);
    } finally {
        try {
            statement.close();
            baglanti.close();
        } catch (SQLException ex) {
          
        }
    }
}
    
    
    
    
    
    
    
    private void btnRemoveLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveLineActionPerformed
       
        
    int selectedRow = tblUrunler.getSelectedRow();

    
    if (selectedRow == -1) {
        
         JOptionPane.showMessageDialog(this, "Lütfen bir satır seçin.", "Uyarı", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    int silinecekStokNo = (int) model.getValueAt(selectedRow, 0);

   
    model.removeRow(selectedRow);

    
    veritabanindanKaydiKaldır(silinecekStokNo);
        
        
        
        
    }//GEN-LAST:event_btnRemoveLineActionPerformed

    private void btnSiparisVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiparisVerActionPerformed
      
        Siparişler siparişler = new Siparişler();
        
        this.setVisible(false);
        
        siparişler.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_btnSiparisVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        KullaniciGiris kullaniciGiris = new KullaniciGiris();
        this.setVisible(false);
        kullaniciGiris.setVisible(true);
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtStokCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemoveLine;
    private javax.swing.JButton btnSiparisVer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCinsiyet;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbName;
    private javax.swing.JComboBox<String> cmbSize;
    private javax.swing.JComboBox<String> cmbUpdateCinsiyet;
    private javax.swing.JComboBox<String> cmbUpdateColor;
    private javax.swing.JComboBox<String> cmbUpdateName;
    private javax.swing.JComboBox<String> cmbUpdateSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblStokCount;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUpdateColor;
    private javax.swing.JLabel lblUpdateName;
    private javax.swing.JLabel lblUpdateSize;
    private javax.swing.JLabel lblUpdateStokCount;
    private javax.swing.JLabel lblUpdateStokNo;
    private javax.swing.JTable tblUrunler;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStokCount;
    private javax.swing.JTextField txtUpdateStokCount;
    private javax.swing.JTextField txtUpdateStokNo;
    // End of variables declaration//GEN-END:variables
}
